language: node_js
node_js:
- '5'
env:
- NODE_ENV=TEST CXX=g++-4.8
addons:
  postgresql: '9.4'
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
- postgresql
before_script:
- psql -c 'create database aws;' -U postgres
- sleep 15
install:
- travis_retry npm install -g node-gyp
- travis_retry npm install
- sleep 15
script:
- travis_retry npm run build
- travis_retry npm run lint
- travis_retry npm test
after_success:
- chmod 600 deploy-key
- mv deploy-key ~/.ssh/id_rsa
- rm -rf src/
- rm -rf node_modules/
- tar -czf jseminck-be-api-authentication.tgz .
- scp jseminck-be-api-authentication.tgz deploy@95.85.25.10:/home/apps/
- scp deploy.sh deploy@95.85.25.10:/home/apps/
- ssh deploy@95.85.25.10 'chmod +x /home/apps/deploy.sh'
- ssh deploy@95.85.25.10 './home/apps/deploy.sh'
before_install:
- openssl aes-256-cbc -K $encrypted_37c42d1fc8f1_key -iv $encrypted_37c42d1fc8f1_iv
  -in deploy-key.enc -out deploy-key -d
